[tool.poetry]
name = "tikapi-test"
version = "0.1.0"
description = ""
authors = ["Ezequiel Bravo <ebravo@avocadoblock.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
tikapi = "^3.1.60"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
